name: Pull Request CI

on:
  pull_request:
    branches:
      - master

env:
  rid: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true

      - name: Validate Dependencies
        id: validate-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.validate-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Cache Dependencies
        uses: actions/cache@v2
        if: steps.validate-dependencies.outputs.cache-hit != 'true'
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Cypress
        uses: actions/cache@v2
        if: steps.validate-dependencies.outputs.cache-hit != 'true'
        with:
          path: /home/runner/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}


  test-source:
    name: Test - Source
    needs: initialize
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true

      - name: Uncache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Test Source
        run: yarn ci:test:src

  test-static:
    name: Test - static
    needs: initialize
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true

      - name: Uncache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: test-static
        run: yarn ci:test:lint

  build-source:
    name: Build - Source
    needs: initialize
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      
      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true

      - name: Uncache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build Source
        run: yarn ci:build

      - name: Cache Dist
        uses: actions/cache@v2
        with:
          path: dist/
          key: dist-${{ runner.os }}-${{ env.rid }}

      - name: Cache Docs
        uses: actions/cache@v2
        with:
          path: docs/
          key: docs-${{ runner.os }}-${{ env.rid }}

  test-storybook:
    name: Test - Storybook
    needs: build-source
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true

      - name: Uncache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Uncache Dist
        uses: actions/cache@v2
        with:
          path: dist/
          key: dist-${{ runner.os }}-${{ env.rid }}

      - name: Uncache Docs
        uses: actions/cache@v2
        with:
          path: docs/
          key: docs-${{ runner.os }}-${{ env.rid }}

      - name: Test - Storybook
        uses: percy/storybook-action@v0.1.6
        with:
          custom-command: 'yarn ci:test:storybook'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  test-examples:
    name: Test - Examples
    needs: build-source
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          check-latest: true

      - name: Uncache Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Uncache Cypress
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Uncache Dist
        uses: actions/cache@v2
        with:
          path: dist/
          key: dist-${{ runner.os }}-${{ env.rid }}

      - name: Uncache Docs
        uses: actions/cache@v2
        with:
          path: docs/
          key: docs-${{ runner.os }}-${{ env.rid }}

      - name: Test - Examples
        uses: cypress-io/github-action@v2
        with:
          command: yarn ci:test:examples
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
